#!/bin/bash

# Generated by tmuxgen – sets up a tmux session per config
# Tip: alias it, e.g., alias work='/path/to/generated.sh'

SESSION_NAME=my_session
SESSION_PATH=/home/eiger/workspace

# Create a new detached session with the first window
tmux new-session -d -s my_session -c /home/eiger/workspace -n nv-ws

# Actions for window: nv-ws
tmux send-keys -t my_session:nv-ws -l 'nv .'
tmux send-keys -t my_session:nv-ws Enter
sleep 0.080
tmux send-keys -t my_session:nv-ws Space e Space q s Space e

# Create window: ws
tmux new-window -t my_session -c /home/eiger/workspace -n ws

# Create window: cmu
tmux new-window -t my_session -c /home/eiger/CMU/2025_Fall -n cmu

# Create window: blog
tmux new-window -t my_session -c /home/eiger/Blog/myblog/ -n blog
# Actions for window: blog
tmux send-keys -t my_session:blog -l 'nv .'
tmux send-keys -t my_session:blog Enter

# Focus window: nv-ws
tmux select-window -t my_session:nv-ws

# Attach to session
tmux attach-session -t my_session
